name: Validate One Click Apps

on:
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: 20
                  cache: npm
            - run: npm ci
            - run: npm run validate_apps
            - run: npm run formatter
            - run: npm run build
